### ISSUE TITLE
Improve pictures in Sec.4 and 5 of RDF 1.2 Semantics

### ISSUE THREAD

**Issue by Antoine-Zimmermann** [w3c/rdf-semantics#42]
The pictures used in Section 4.1 and Section 5.1.1 are pixelated and not looking nice. Vector graphics version should be produced and used.

**Comment by pfps** [comment]
Anyone can feel free to improve the graphics.

**Comment by TallTed** [comment]
I guess you mean these from [4.1 Shared blank nodes, unions and merges](https://w3c.github.io/rdf-semantics/spec/#unions_merges) —

* example1.jpg
  ![example1.jpg](https://w3c.github.io/rdf-semantics/spec/RDF12SemanticsDiagrams/example1.jpg)
* example2.jpg
  ![example2.jpg](https://w3c.github.io/rdf-semantics/spec/RDF12SemanticsDiagrams/example2.jpg)
* example4.jpg
  ![example4.jpg](https://w3c.github.io/rdf-semantics/spec/RDF12SemanticsDiagrams/example4.jpg)
* example3.jpg
  ![example3.jpg](https://w3c.github.io/rdf-semantics/spec/RDF12SemanticsDiagrams/example3.jpg)

— and these from [5.1.1 Shared blank nodes (Informative)](https://w3c.github.io/rdf-semantics/spec/#shared_blank_nodes) —

* example5.jpg
  ![example5.jpg](https://w3c.github.io/rdf-semantics/spec/RDF12SemanticsDiagrams/example5.jpg)

Yeah, these are terrible. JPG should never be used for such diagrams!

They should be fairly quick to recreate (and improve). Optimal replacements will be SVG with clear prose describing them to go alongside for a11y. What's the preferred tool these days?

**Comment by gkellogg** [comment]
I've used Google Docs to create many images such as this. For example [quoted triple](https://docs.google.com/drawings/d/1I_QxbUgnQXumXzb8c0WNJHIQ-mtRs2S80dDG6i9aOD8/edit?pli=1) used in RDF Concepts.

![quoted-triple](https://github.com/w3c/rdf-semantics/assets/46296/5b3614dc-905e-4597-8350-d19e0eca6847)

I then export the SVG and put it in the document directory, with a link back to the source for future reference. For example:

    <figure id="fig-quoted-triple">
      <a href="quoted-triple.svg">
        
        <img src="quoted-triple.svg"
             alt="An RDF graph containing a triple that references an unasserted quoted triple (with grey background) as the subject"
             style="width:70%"
             aria-describedby="fig-quoted-triple-alt"/>
      </a>
      <figcaption id="fig-quoted-triple-alt">
        An RDF graph containing a triple that references an unasserted quoted triple (with grey background) as the subject.
      </figcaption>
    </figure>

In this case, you could take a base drawing, and save it one for each figure. Make sure to make it publicly accessible and to allow edit writes so that it can be changed in the future.

Note the accessibility requirements for an alt description and description. Typically, the figure caption is adequate, but there are other ways to do this.

**Comment by pfps** [comment]
The pictures were added and this issue is editorial and has been lingering so I'm closing it.
